// Package logic provides ...
package logic

import (
	"github.com/glepnir/jarvis/internal/vim"
	"github.com/glepnir/jarvis/pkg/util"
)

func RunLogic() error {
	util.EnsureFoldersExist(vim.ConfPath, vim.ConfCore, vim.ConfAutoload, vim.ConfModules, vim.CachePath)
	r := PluginManage()
	vim.Leaderkey = LeaderKey()
	vim.LocalLeaderKey = LocalLeaderKey()
	vim.Colorscheme = Colorscheme()
	vim.StartScreenPlugin = DashboardPlugin()
	vim.StatusLine = SpacelinePlugin()
	vim.BufferLine = BufferLinePlugin()
	vim.Explorer = ExplorerPlugin()
	vim.Database = DatabasePlugin()
	vim.Fuzzyfind = FuzzyFindPlugin()
	vim.EditorConfig = EditorConfigPlugin()
	vim.IndentPlugin = IndentLinePlugin()
	vim.CommentPlugin = CommentPlugin()
	vim.OutLinePlugin = ViewSymbolsPlugin()
	vim.TagsPlugin = GentagsPlugin()
	vim.QuickRun = QuickRunPlugin()
	vim.DataTypeFile = DataTypeFile()
	vim.EnhancePlugins = EnhancePlugin()
	vim.SandwichPlugin = SandWichPlugin()
	vim.VersionControlPlugin = VersionControlPlugin()
	vim.UserLanguages = LanguageServerProtocol()
	r.GenerateInit()
	r.GenerateCore(vim.Leaderkey, vim.LocalLeaderKey, vim.LeaderKeyMap)
	r.GeneratePlugMan()
	r.GenerateGeneral()
	r.GenerateAutoloadFunc()
	r.GeneratePluginFolder()
	r.GenerateTheme()
	r.GenerateCacheTheme(vim.Colorscheme, vim.ColorschemeMap)
	r.GenerateColorscheme(vim.Colorscheme)
	r.GenerateDashboard(vim.StartScreenPlugin)
	r.GenerateBufferLine(vim.BufferLine)
	r.GenerateStatusLine(vim.StatusLine)
	r.GenerateExplorer(vim.Explorer)
	r.GenerateDatabase(vim.Database)
	r.GenerateFuzzyFind(vim.Fuzzyfind)
	r.GenerateEditorConfig(vim.EditorConfig)
	r.GenerateIndentLine(vim.IndentPlugin)
	r.GenerateComment(vim.CommentPlugin)
	r.GenerateOutLine(vim.OutLinePlugin)
	r.GenerateTags(vim.TagsPlugin)
	r.GenerateQuickRun(vim.QuickRun)
	r.GenerateDataTypeFile(vim.DataTypeFile, vim.DataFileMap)
	r.GenerateEnhanceplugin(vim.EnhancePlugins, vim.EnhancePluginMap)
	r.GenerateSandWich(vim.SandwichPlugin)
	r.GenerateTextObj()
	r.GenerateVersionControl(vim.VersionControlPlugin, vim.VersionControlMap)
	r.GenerateCocJson()
	r.GenerateVimMap()
	r.GenerateLanguagePlugin(vim.UserLanguages, vim.LanguagesPluginMap)
	return nil
}
